# Generated by Django 5.2.8 on 2025-11-11 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('log_type', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='uploaded_logs/')),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
